#define BOMBS_HEIGHT 22
#define BOMBS_WIDTH 80
#define BOMBL_HEIGHT 24
#define BOMBL_WIDTH 80

#define BOMBS1  "                                                          ++             ++     "
#define BOMBS2  "                                               ++          ++         ++        "
#define BOMBS3  "                                                   ++       ++     ++           "
#define BOMBS4  "                                                        ++                      "
#define BOMBS5  "                            ++++++++++++++++++++                    ++  ++  ++  "
#define BOMBS6  "                          ++                    ++++      ++++++                "
#define BOMBS7  "                        ++                          ++++++                      "
#define BOMBS8  "                        ++                                          ++          "
#define BOMBS9  "                    ++++++++++                          ++    ++      ++        "
#define BOMBS10 "                    ++++++++++                        ++                ++      "
#define BOMBS11 "                  +++++++++++++++                   ++        ++          ++    "
#define BOMBS12 "                +++++++++++++++++++                                             "
#define BOMBS13 "              +++++++++++++++++++++++                         ++                "
#define BOMBS14 "            +++++++++++++++++++++++++++                                         "
#define BOMBS15 "          +++++++++++++++++++++++++++++++                                       "
#define BOMBS16 "          +++++++++++++++++++++++++++++++                                       "
#define BOMBS17 "          +++++++++++++++++++++++++++++++                                       "
#define BOMBS18 "            +++++++++++++++++++++++++++                                         "
#define BOMBS19 "              +++++++++++++++++++++++                                           "
#define BOMBS20 "                +++++++++++++++++++                                             "
#define BOMBS21 "                  +++++++++++++++                                               "
#define BOMBS22 "                      +++++++                                                   "
  
#define BOMBL1  "                                                          ++             ++     "
#define BOMBL2  "                                               ++          ++         ++        "
#define BOMBL3  "                                                   ++       ++     ++           "
#define BOMBL4  "                                                        ++                      "
#define BOMBL5  "                            ++++++++++++++++++++                    ++  ++  ++  "
#define BOMBL6  "                          ++                    ++++      ++++++                "
#define BOMBL7  "                        ++                          ++++++                      "
#define BOMBL8  "                        ++                                          ++          "
#define BOMBL9  "                  ++++++++++++++                        ++    ++      ++        "
#define BOMBL10 "                  ++++++++++++++                      ++                ++      "
#define BOMBL11 "              +++++++++++++++++++++++               ++        ++          ++    "
#define BOMBL12 "          +++++++++++++++++++++++++++++++                                       "
#define BOMBL13 "          +++++++++++++++++++++++++++++++                     ++                "
#define BOMBL14 "        +++++++++++++++++++++++++++++++++++                                     "
#define BOMBL15 "        +++++++++++++++++++++++++++++++++++                                     "
#define BOMBL16 "      +++++++++++++++++++++++++++++++++++++++                                   "
#define BOMBL17 "      +++++++++++++++++++++++++++++++++++++++                                   "
#define BOMBL18 "      +++++++++++++++++++++++++++++++++++++++                                   "
#define BOMBL19 "        +++++++++++++++++++++++++++++++++++                                     "
#define BOMBL20 "        +++++++++++++++++++++++++++++++++++                                     "
#define BOMBL21 "          +++++++++++++++++++++++++++++++                                       "
#define BOMBL22 "          +++++++++++++++++++++++++++++++                                       "
#define BOMBL23 "              +++++++++++++++++++++++                                           "
#define BOMBL24 "                  +++++++++++++++                                               "